version: '3.7'
services:
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - '8081:8081'
    volumes:
      - nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
volumes:
  nexus_data:
    driver: local